name: "Fix coding standards violations"

on:
  workflow_call:
    inputs:
      php-version:
        description: "The PHP version to use when running the job"
        default: "8.2"
        required: false
        type: "string"

jobs:
  fix-coding-standards-violations:
    name: "Fix coding standard violations"
    runs-on: "${{ matrix.os }}"

    strategy:
      matrix:
        os: [ "ubuntu-22.04" ]
        php-version: [ "${{ inputs.php-version }}" ]

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: "${{ matrix.php-version }}"
          coverage: "none"

      - name: "Install dependencies with Composer"
        uses: "ramsey/composer-install@v3"

      - name: "Apply coding standards"
        run: "vendor/bin/php-cs-fixer fix --no-interaction --ansi --allow-risky=yes --diff --verbose"

      - name: "Get branch name"
        uses: "tj-actions/branch-names@v8"
        id: "branch-name"

      - name: "Create and push commit"
        if: "steps.branch-name.outputs.is_default == 'false'"
        uses: "stefanzweifel/git-auto-commit-action@v4"
        with:
          commit_message: "Apply coding standards"

      - name: "Create pull request"
        if: "steps.branch-name.outputs.is_default == 'true'"
        uses: "peter-evans/create-pull-request@v5"
        with:
          commit-message: "Apply coding standards"
          branch: "php-cs-fixer"
          delete-branch: true
          title: 'Apply coding standards'
          draft: false
          base: "${{ steps.branch-name.outputs.default_branch }}"
